##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/libmateweather
    - aptitude
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - gtk-doc-tools
    - libglib2.0-dev
    - libgtk-3-dev
    - libsoup-gnome2.4-dev
    - libsoup2.4-dev
    - libxml2-dev
    - libxml2-utils
    - make
    - mate-common
    - tzdata

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
